export const GET_PALLETE = "GET_PALLETE";
export type GET_PALLETE = typeof GET_PALLETE;

export const GET_PALETTES = "GET_PALETTES";
export type GET_PALETTES = typeof GET_PALETTES;

export const GET_COLOR = "GET_COLOR";
export type GET_COLOR = typeof GET_COLOR;

export const GET_COLORS = "GET_COLORS";
export type GET_COLORS = typeof GET_COLORS;

export const GET_USER = "GET_USER";
export type GET_USER = typeof GET_USER;

export const GET_USERS = "GET_USERS";
export type GET_USERS = typeof GET_USERS;

export const GET_FAVORITE_PALETTE_IDS = "GET_FAVORITE_PALETTE_IDS";
export type GET_FAVORITE_PALETTE_IDS = typeof GET_FAVORITE_PALETTE_IDS;

export const GET_FAVORITE_COLOR_IDS = "GET_FAVORITE_COLOR_IDS";
export type GET_FAVORITE_COLOR_IDS = typeof GET_FAVORITE_COLOR_IDS;

export const FAVORITE_COLOR = "FAVORITE_COLOR";
export type FAVORITE_COLOR = typeof FAVORITE_COLOR;

export const UNFAVORITE_COLOR = "UNFAVORITE_COLOR";
export type UNFAVORITE_COLOR = typeof UNFAVORITE_COLOR;

export const FAVORITE_PALETTE = "FAVORITE_PALETTE";
export type FAVORITE_PALETTE = typeof FAVORITE_PALETTE;

export const UNFAVORITE_PALETTE = "UNFAVORITE_PALETTE";
export type UNFAVORITE_PALETTE = typeof UNFAVORITE_PALETTE;

export const GET_RANDOM_OBJECT = "GET_RANDOM_OBJECT";
export type GET_RANDOM_OBJECT = typeof GET_RANDOM_OBJECT;

export const GET_OBJECT_COLORS = "GET_OBJECT_COLORS";
export type GET_OBJECT_COLORS = typeof GET_OBJECT_COLORS;

export const GET_COLOR_PALETTES_LIST = "GET_COLOR_PALETTES_LIST";
export type GET_COLOR_PALETTES_LIST = typeof GET_COLOR_PALETTES_LIST;

export const GET_COLOR_PALETTE_INFO = "GET_COLOR_PALETTE_INFO";
export type GET_COLOR_PALETTE_INFO = typeof GET_COLOR_PALETTE_INFO;
